#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

binaries=(
	wget
	mtr
	aircrack-ng
	nmap
	lft
	mc
	wakeonlan
	ssh-copy-id
	unarj
	mackup
	java
)

echo "Installing binaries..."
brew install ${binaries[@]}

echo "Installing Homebrew Cask.."
brew install caskroom/cask/brew-cask

apps=(
            1password
            appcleaner
            bartender
            cakebrew
            cocktail
            controlplane
            daisydisk
            disablemonitor
            dropbox
            evernote
            filebot
            firefox
            github
            google-chrome
	    google-drive
            iterm2
            istat-menus
            jdownloader
            launchcontrol
            little-snitch
	    mackup
            mediaelch
	    minitimer
	    moom
            omnifocus
            osxfuse
            path-finder
            rclone
            sdformatter
            skype
	    slack
	    stay
            tableau
            the-unarchiver
            transmission-remote-gui
            tunnelblick
	    vagrant
	    vagrant-manager
            vlc
	    virtualbox
            witgui
)

echo "Installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}

