#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

binaries=(
	wget
	mtr
	aircrack-ng
	nmap
	lft
	mc
	wakeonlan
	ssh-copy-id
	unarj
	mackup
	java
)

echo "Installing binaries..."
brew install ${binaries[@]}

echo "Installing Homebrew Cask.."
brew install caskroom/cask/brew-cask

apps=(
            1password
            appcleaner
            bartender
            cakebrew
            cocktail
            controlplane
            crashplan
            daisydisk
            disablemonitor
            dropbox
            evernote
            filebot
            firefox
            github
            google-chrome
            iterm2
            istat-menus
            jdownloader
            launchcontrol
            little-snitch
            mediaelch
            minitimer
            omnifocus
            osxfuse
            parallels-desktop
            path-finder
            rclone
            sdformatter
            skype
	    stay
	    ssh-copy-id
            tableau
            the-unarchiver
            transmission-remote-gui
            tunnelblick
            vlc
            vmware-fusion
            witgui
)

echo "Installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}

