#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

binaries=(
	wget
	mtr
	aircrack-ng
	nmap
	lft
	mc
	wakeonlan
	ssh-copy-id
	unarj
	mackup
	java
)

echo "Installing binaries..."
brew install ${binaries[@]}

echo "Installing Homebrew Cask.."
brew install caskroom/cask/brew-cask

applications=(
            iterm2
            dropbox
            vlc
            skype
            google-chrome
            the-unarchiver
            path-finder
            cakebrew
            1password
            evernote
            istat-menus
            firefox
            vmware-fusion
            parallels-desktop
            jdownloader
            omnifocus
            mediaelch
            viscosity
            crashplan
            tableau
            transmission-remote-gui
            sdformatter
            appcleaner
            daisydisk
            github
            tunnelblick
            minitimer
            cocktail
            little-snitch
            bartender
            filebot
            controlplane
)

echo "Installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}

