#!/bin/bash
sudo apt-get update
sudo apt-get upgrade
#Rpi Monitor
sudo apt-get install apt-transport-https ca-certificates
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2C0D3C0F 
sudo wget http://goo.gl/rsel0F -O /etc/apt/sources.list.d/rpimonitor.list
sudo apt-get update
sudo apt-get install rpimonitor
sudo /usr/share/rpimonitor/scripts/updatePackagesStatus.pl
